/* eslint-disable @next/next/no-img-element */
// import PropTypes from "prop-types";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { useEffect } from "react";
// import { useState } from "react";
import Head from "next/head";
import Link from "next/link"; // Import the Link component
import IconButton from "@mui/material/IconButton";
import Button from "@mui/material/Button";
import HomeIcon from "@mui/icons-material/Home";
import AccountCircleIcon from "@mui/icons-material/AccountCircle";
import { authenticated } from "../../lib/middleware";
import DormMaps from "../../components/dormMaps";
import styles from "../../styles/main.module.css";
import DormSearchBar from "../../components/DormSearchBar";

export default function DormView() {
  const router = useRouter();
  const { data: session } = useSession();

  const { name } = router.query;

  useEffect(() => {
    if (!session) {
      router.push("/login");
    }
  }, [session, router]);

  return (
    <>
      <Head>
        <title>MiddHousing</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.body}>
        <div className={styles.otherButtonsContainer}>
          <Link href="/">
            <IconButton
              aria-label="Back to Home"
              className={styles.backButton2}
            >
              <HomeIcon style={{ fontSize: "2rem", color: "0074b3" }} />
            </IconButton>
          </Link>
          <div className={styles.title}>
            <img
              className={styles.pantherImage}
              height={100}
              width={300}
              src="/images/panther.png"
              alt="panther"
            />
            <h3>Middlebury Housing</h3>
          </div>
          <Link href="/profile">
            <Button
              variant="contained"
              startIcon={<AccountCircleIcon style={{ fontSize: "2rem" }} />}
              className={styles.profileButton}
            >
              My Profile
            </Button>
          </Link>
        </div>
        <section className={styles.container}>
          <div className={styles.leftHalf}>
            <article className={styles.stuff}>
              <DormSearchBar />
            </article>
          </div>
          <div className={styles.rightHalf}>
            <DormMaps selectedDorm={name} />
          </div>
        </section>
      </main>
    </>
  );
}

DormView.middleware = [authenticated];
