import Head from "next/head";
import SearchBar from "@/components/SearchBar";
import InteractiveMap from "@/components/InteractiveMap";
import styles from "../styles/main.module.css";

const dorms = [
  "Battel",
  "Allen",
  "Hepburn",
  "Stewart",
  "Cook",
  "Gifford",
  "Hadley",
  "Hillcrest",
  "Milliken",
  "Painter",
  "Palmer",
  "Ross",
  "Sunderland",
  "Wright",
  "Atwater",
  "Chellis",
  "Coffrin",
  "Larocque",
  "Munroe",
  "Pearsons",
];

export default function Home() {
  return (
    <>
      <Head>
        <title>MiddHousing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <div className={styles.h1}>Middlebury Housing</div>
        <section className={styles.container}>
          <div className={styles.leftHalf}>
            <article>
              <h2>Search Bar Area</h2>
              <SearchBar dorms={dorms} />
            </article>
          </div>
          <div className={styles.rightHalf}>
            <InteractiveMap />
          </div>
        </section>
      </main>
    </>
  );
}
