import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/rooms.module.css";

export default function Rooms() {
  const [dormName, setDormName] = useState(null);
  const [dormDimensions, setDormDimensions] = useState(null);
  const [dormReview, setDormReview] = useState(null);
  const [dormRating, setDormRating] = useState(null);
  const [dormNumber, setDormNumber] = useState(null);

  async function getRoom(Room) {
    if (!Room) {
      setDormName("Stewart");
      setDormDimensions(173);
      setDormReview("Comfortable and clean room.");
      setDormRating(4);
      setDormNumber(123);
    } else {
      try {
        const response = await fetch("/api/rooms", {
          method: "GET",
          headers: new Headers({
            Accept: "application/json",
            "Content-Type": "application/json",
          }),
        });
        if (response.ok) {
          const data = await response.json();
          setDormName(data.name);
          setDormDimensions(data.dimensions);
          setDormReview(data.review);
          setDormRating(data.rating);
        }
      } catch (error) {
        console.log("Something went wrong");
      }
    }
  }

  useEffect(() => {
    getRoom();
  }, []);

  return (
    <>
      <Head>
        <title>MiddHousing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <div className={styles.h1}>{dormName}</div>
        <div className={styles.h2}> Room : {dormNumber} </div>
        <div className={styles.h2}> Dimensions : {dormDimensions} </div>
        <div className={styles.h2}> Reviews : {dormReview} </div>
        <div className={styles.h2}> Rating : {dormRating} </div>
        <div class="rating-box">
          <div class="stars">
            <i class="fa-solid fa-star" />
            <i class="fa-solid fa-star" />
            <i class="fa-solid fa-star" />
            <i class="fa-solid fa-star" />
            <i class="fa-solid fa-star" />
          </div>
        </div>
      </main>
    </>
  );
}
