import Head from "next/head";
import Image from "next/image"; // Import the Image component
import { useEffect, useState } from "react";
import styles from "../styles/rooms.module.css";
import battell from "../../public/images/battell.png";

export default function Rooms() {
  const [dormName, setDormName] = useState(null);
  const [dormDimensions, setDormDimensions] = useState(null);
  const [dormReview, setDormReview] = useState(null);
  const [dormRating, setDormRating] = useState(null);
  const [dormNumber, setDormNumber] = useState(null);

  async function getRoom(Room) {
    // how would this function with this being called elsewhere, like when do we tell it what room to call
    if (!Room) {
      setDormName("Stewart");
      setDormDimensions(173);
      setDormReview("Comfortable and clean room.");
      setDormRating(4);
      setDormNumber(123);
    } else {
      try {
        const fetchAddress = `/api/rooms/${Room}`;
        const response = await fetch(fetchAddress, {
          method: "GET",
          headers: new Headers({
            Accept: "application/json",
            "Content-Type": "application/json",
          }),
        });
        if (response.ok) {
          const data = await response.json();
          setDormName(data.name);
          setDormDimensions(data.dimensions);
          setDormReview(data.review);
          setDormRating(data.rating);
        }
      } catch (error) {
        console.log("Something went wrong");
      }
    }
  }

  useEffect(() => {
    getRoom();
  }, []);

  return (
    <>
      <Head>
        <title>MiddHousing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </Head>
      <main className={styles.body}>
        <div className={styles.imageContainer}>
          <Image
            src={battell} // imported up to
            alt="Room Photo"
            width={1008}
            height={672}
          />
        </div>
        <div className={styles.h1}>{dormName}</div>
        <div className={styles.h2}> Room : {dormNumber} </div>
        <div className={styles.h2}> Dimensions : {dormDimensions} sq ft </div>
        <div className={styles.h2}> Rating : {dormRating} </div>
        <div className="rating-box">
          <div className={styles.starscontainer}>
            {Array.from({ length: dormRating }, (_, i) => (
              <i key={i} className="fas fa-star is-active" />
            ))}
            {/* Add unfilled stars */}
            {Array.from({ length: 5 - dormRating }, (_, i) => (
              <i key={i} className="far fa-star unfilled-star" />
            ))}
          </div>
        </div>
        <div className={styles.h2}> Reviews : {dormReview} </div>
      </main>
    </>
  );
}
